name: ResFlex

dependencies:
  - python=3.11
  - numpy>=1.10
  - matplotlib>=1.5.1
  - pandas>=0.24.0
  - pip
  - pip:
    - convertdate
    - holidays
    - plotly
    - scipy
    - openpyxl
    - xarray

 